spring.application.name=skyquest


# datasource
spring.datasource.url=jdbc:postgresql://172.19.0.2:5432/kivexel
spring.datasource.username=marigold
spring.datasource.password=rasputin01
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# security
security.jwt.secret-key=cbf771a6ace58022cfdf6e7a264145907ccfff92d1ed3ef8b9ea55e032078a3f
security.jwt.expiration-time=3600000
