spring.application.name=skyquest


# datasource
spring.datasource.url=jdbc:postgresql://172.19.0.2:5432/kivexel
spring.datasource.username=marigold
spring.datasource.password=rasputin01
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# security
security.jwt.secret-key=je5V5Q9M/AEOAmRx7rb3S+yMLKW9vgHu3QEyQ1HsetN7I9tZUZjrLYRMnoG38jzqWhBMfIC5SiLg7sEn2Bd6zw==
security.jwt.expiration-time=3600000
