server.port=8082
spring.cloud.config.enabled=true

spring.application.name=config-server
spring.cloud.config.server.git.uri=git@gh_personal:ppalazzi/config-server-apps.git

spring.cloud.config.server.git.default-label=develop

spring.cloud.config.server.git.ignore-local-ssh-settings=false
spring.cloud.config.server.git.clone-on-start=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=false
spring.main.allow-bean-definition-overriding=true

